/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package issue201;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

public class AppTest {
	@Test
	public void appHasAGreeting() {
		StringBuilder sb = new StringBuilder();
		ShoppingApp.render(sb);
		String actual = sb.toString();
		System.out.println(actual);
		String expected = """
				
				Here is your order: #123
				====================
				-- TV Set
				-- Books

				test a and b

				other
				""";
		assertEquals(expected, actual);
	}
}
