name: Release with Maven

on:
  workflow_dispatch:

jobs:
  release:

    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: "${{github.run_number}}"
      MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --no-transfer-progress"
      NEXUS_SNAPHOP_COM_PASSWORD: ${{ secrets.NEXUS_SNAPHOP_COM_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17 
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Prepare Release with Maven Release Plugin
        run: |
          DEVELOPMENT_VERSION=$(.m2/version.sh current)
          RELEASE_VERSION=$(.m2/version.sh release $DEVELOPMENT_VERSION $BUILD_NUMBER)
          mvn $MAVEN_CLI_OPTS release:prepare -Dresume=false -DdevelopmentVersion="$DEVELOPMENT_VERSION" -DreleaseVersion="$RELEASE_VERSION"
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
      - name: Perform Release with Maven Release Plugin
        run: mvn $MAVEN_CLI_OPTS release:perform -Dresume=false -DskipTests=true
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
